version: "3"
services:
    # Create backend container
    backend:
        # Create backend container
        build: ./server
        ports:
            - "80:5000"
        container_name: server-docker
        restart: always
        # volumes:
        #     - ./server/:/usr/src/app/server/
        environment:
            - mongoURI=mongodb+srv://new:S09C6SHdOD4zghXG@dev.pw3h5.mongodb.net/Dev?retryWrites=true&w=majority
            - jwtSecret=carden_JwtSecret_Chadweeb_42069
            - NODE_ENV=production
