version: "3"
services:
    # Create frontend container
    frontend: # Name of our service
        build: ./client # path to dockerfile
        ports: # Port binding to host from docker container
            - "3000:3000" # Bind port 3000 of host to 3000 of container
        container_name: client-docker
        restart: always # What to do if container crashes
        links:
            - backend
        volumes:
            - ./client/src:/usr/src/app/client/src
            - ./client/public:/usr/src/app/client/public
        environment:
            - CHOKIDAR_USEPOLLING=true
    # Create backend container
    backend:
        # Create backend container
        build: ./server
        ports:
            - "5000:5000"
        container_name: server-docker
        restart: always
        volumes:
            - ./server/:/usr/src/app/server/
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
